import { useState, useEffect } from 'react';
import { Card, Table, Button, Space, Tag, Modal, Form, DatePicker, Select, message } from 'antd';
import { FileProtectOutlined, DownloadOutlined, EyeOutlined } from '@ant-design/icons';
import type { TableProps } from 'antd';

interface Report {
  id: number;
  type: string;
  status: string;
  generatedAt: string;
  generatedBy: string;
  score: number;
  findings: number;
  recommendations: number;
}

interface ComplianceReportsProps {
  organizationId: number;
}

export function ComplianceReports({ organizationId }: ComplianceReportsProps) {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [modalVisible, setModalVisible] = useState(false);
  const [form] = Form.useForm();

  useEffect(() => {
    fetchReports();
  }, [organizationId]);

  const fetchReports = async () => {
    try {
      const response = await fetch(`/api/organizations/${organizationId}/reports`);
      const result = await response.json();

      if (!result.success) {
        throw new Error(result.error);
      }

      setReports(result.data);
    } catch (error) {
      console.error('Error fetching reports:', error);
      message.error('Failed to fetch reports');
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateReport = async (values: any) => {
    try {
      const response = await fetch(`/api/organizations/${organizationId}/reports`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(values),
      });

      const result = await response.json();

      if (!result.success) {
        throw new Error(result.error);
      }

      message.success('Report generation started');
      setModalVisible(false);
      form.resetFields();
      fetchReports();
    } catch (error) {
      console.error('Error generating report:', error);
      message.error('Failed to generate report');
    }
  };

  const handleDownload = async (reportId: number) => {
    try {
      const response = await fetch(
        `/api/organizations/${organizationId}/reports/${reportId}/download`
      );
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `compliance-report-${reportId}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      console.error('Error downloading report:', error);
      message.error('Failed to download report');
    }
  };

  const columns: TableProps<Report>['columns'] = [
    {
      title: 'Type',
      dataIndex: 'type',
      key: 'type',
      render: (type) => (
        <Tag color="blue">{type}</Tag>
      ),
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (status) => {
        const color = status === 'COMPLETED' ? 'green' : status === 'FAILED' ? 'red' : 'gold';
        return <Tag color={color}>{status}</Tag>;
      },
    },
    {
      title: 'Generated At',
      dataIndex: 'generatedAt',
      key: 'generatedAt',
    },
    {
      title: 'Generated By',
      dataIndex: 'generatedBy',
      key: 'generatedBy',
    },
    {
      title: 'Score',
      dataIndex: 'score',
      key: 'score',
      render: (score) => (
        <Tag color={score >= 80 ? 'green' : score >= 60 ? 'gold' : 'red'}>
          {score}%
        </Tag>
      ),
    },
    {
      title: 'Findings',
      dataIndex: 'findings',
      key: 'findings',
    },
    {
      title: 'Actions',
      key: 'actions',
      render: (_, record) => (
        <Space>
          <Button
            icon={<EyeOutlined />}
            onClick={() => window.location.href = `/organizations/${organizationId}/reports/${record.id}`}
          >
            View
          </Button>
          <Button
            icon={<DownloadOutlined />}
            onClick={() => handleDownload(record.id)}
            disabled={record.status !== 'COMPLETED'}
          >
            Download
          </Button>
        </Space>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <Card>
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-xl font-semibold">Compliance Reports</h2>
          <Button
            type="primary"
            icon={<FileProtectOutlined />}
            onClick={() => setModalVisible(true)}
          >
            Generate Report
          </Button>
        </div>

        <Table
          columns={columns}
          dataSource={reports}
          rowKey="id"
          loading={loading}
          pagination={{ pageSize: 10 }}
        />
      </Card>

      <Modal
        title="Generate Compliance Report"
        open={modalVisible}
        onCancel={() => setModalVisible(false)}
        footer={null}
      >
        <Form
          form={form}
          onFinish={handleGenerateReport}
          layout="vertical"
        >
          <Form.Item
            name="type"
            label="Report Type"
            rules={[{ required: true, message: 'Please select a report type' }]}
          >
            <Select>
              <Select.Option value="QUARTERLY">Quarterly Report</Select.Option>
              <Select.Option value="ANNUAL">Annual Report</Select.Option>
              <Select.Option value="AUDIT">Audit Report</Select.Option>
            </Select>
          </Form.Item>

          <Form.Item
            name="period"
            label="Period"
            rules={[{ required: true, message: 'Please select a period' }]}
          >
            <DatePicker.RangePicker style={{ width: '100%' }} />
          </Form.Item>

          <Form.Item className="mb-0">
            <Space className="w-full justify-end">
              <Button onClick={() => setModalVisible(false)}>
                Cancel
              </Button>
              <Button type="primary" htmlType="submit">
                Generate
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
} 